import React, { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import Navbar from '../components/Navbar';
import galleryService from '../services/galleryService';
import memberService from '../services/memberService';
import { API_ORIGIN } from '../services/api';
import { useFamilyTree } from '../contexts/FamilyTreeContext';

export default function Gallery() {
    const navigate = useNavigate();
    const { hasPermission } = useFamilyTree();
    const canManage = hasPermission('gallery.manage');
    const [images, setImages] = useState([]); const [members, setMembers] = useState([]);
    const [selected, setSelected] = useState(null); const [file, setFile] = useState(null);
    const [form, setForm] = useState({ caption: '', notes: '', memberId: '' }); const [error, setError] = useState(''); const [loading, setLoading] = useState(true);
    const [formOpen, setFormOpen] = useState(false); const [saving, setSaving] = useState(false);
    const asset = path => path?.startsWith('http') ? path : `${API_ORIGIN}${path}`;
    const load = async () => { setLoading(true); try { const [imageData, memberData] = await Promise.all([galleryService.getImages(), memberService.getMembers()]); setImages(imageData); setMembers(memberData); } catch (exception) { setError(exception.response?.data?.message || 'Không thể tải thư viện.'); } finally { setLoading(false); } };
    useEffect(() => { load(); }, []);
    const upload = async event => { event.preventDefault(); if (!file || !canManage) return; setError(''); setSaving(true); const data = new FormData(); data.append('file', file); data.append('caption', form.caption); data.append('notes', form.notes); if (form.memberId) data.append('memberId', form.memberId); try { await galleryService.upload(data); setFile(null); setForm({ caption: '', notes: '', memberId: '' }); setFormOpen(false); event.target.reset(); await load(); } catch (exception) { setError(exception.response?.data?.message || 'Không thể tải ảnh lên.'); } finally { setSaving(false); } };
    const remove = async image => { if (!canManage || !window.confirm('Xóa ảnh này?')) return; try { await galleryService.delete(image.id); setSelected(null); await load(); } catch (exception) { setError(exception.response?.data?.message || 'Không thể xóa ảnh.'); } };
    return <div className="page"><Navbar /><main className="page-content">
        <div className="content-header-row"><div className="section-header"><h1 className="section-title">Thư viện dòng họ</h1><p className="section-sub">Lưu giữ hình ảnh và những câu chuyện của gia đình.</p></div><div className="content-header-actions">{canManage && <button className="btn btn-primary" onClick={() => setFormOpen(true)}>+ Thêm ảnh</button>}</div></div>
        {canManage && formOpen && <div className="dialog-overlay" role="presentation" onMouseDown={event => event.target === event.currentTarget && setFormOpen(false)}><form className="dialog" onSubmit={upload}><div className="dialog-header"><h2>Thêm ảnh vào thư viện</h2><button type="button" className="dialog-close" onClick={() => setFormOpen(false)} aria-label="Đóng">×</button></div><div className="dialog-body"><div className="dialog-form-grid"><label className="dialog-field dialog-field--wide">Chọn ảnh<input className="input" type="file" accept="image/jpeg,image/png,image/webp,image/gif" required onChange={event => setFile(event.target.files?.[0] || null)} /></label><label className="dialog-field">Chú thích<input className="input" value={form.caption} onChange={event => setForm({ ...form, caption: event.target.value })} placeholder="Tên hoặc nội dung ảnh" /></label><label className="dialog-field">Gắn thành viên<select className="input" value={form.memberId} onChange={event => setForm({ ...form, memberId: event.target.value })}><option value="">Không gắn</option>{members.map(member => <option key={member.id} value={member.id}>{member.fullName}</option>)}</select></label><label className="dialog-field dialog-field--wide">Ghi chú<textarea className="input" style={{ minHeight: 110, paddingTop: 11, resize: 'vertical' }} value={form.notes} onChange={event => setForm({ ...form, notes: event.target.value })} placeholder="Ghi chú về ảnh..." /></label></div></div><div className="dialog-footer"><button type="button" className="btn btn-secondary" onClick={() => setFormOpen(false)} disabled={saving}>Hủy</button><button type="submit" className="btn btn-primary" disabled={!file || saving}>{saving ? 'Đang tải...' : 'Lưu ảnh'}</button></div></form></div>}
        {error && <div className="alert alert-error" style={{ marginBottom: 16 }}>{error}</div>}
        {loading ? <div style={{ padding: 50, textAlign: 'center' }}>Đang tải thư viện...</div> : <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(190px, 1fr))', gap: 16 }}>{images.map(image => <button key={image.id} onClick={() => setSelected(image)} style={{ padding: 0, border: '1px solid var(--color-border)', background: 'var(--color-surface)', borderRadius: 10, overflow: 'hidden', textAlign: 'left', cursor: 'pointer', boxShadow: '0 3px 12px rgba(0,0,0,.08)' }}><img src={asset(image.fileUrl)} alt={image.caption || image.fileName} style={{ display: 'block', width: '100%', aspectRatio: '4 / 3', objectFit: 'cover' }} /><div style={{ padding: 12 }}><strong style={{ display: 'block', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>{image.caption || image.fileName}</strong><span style={{ color: 'var(--color-text-muted)', fontSize: '.8rem' }}>{image.memberName || 'Dòng họ'}</span></div></button>)}</div>}
        {!loading && images.length === 0 && <div className="card" style={{ padding: 45, textAlign: 'center', color: 'var(--color-text-muted)' }}>Chưa có ảnh trong thư viện.</div>}
        {selected && <div role="dialog" aria-modal="true" onClick={() => setSelected(null)} style={{ position: 'fixed', inset: 0, zIndex: 1000, background: 'rgba(0,0,0,.78)', display: 'flex', alignItems: 'center', justifyContent: 'center', padding: 20 }}><div onClick={event => event.stopPropagation()} style={{ maxWidth: 900, width: '100%', maxHeight: '90vh', overflow: 'auto', background: 'var(--color-surface)', borderRadius: 12, padding: 16 }}><img src={asset(selected.fileUrl)} alt={selected.caption || selected.fileName} style={{ display: 'block', maxWidth: '100%', maxHeight: '65vh', margin: '0 auto', objectFit: 'contain' }} /><h2 style={{ margin: '16px 0 6px' }}>{selected.caption || selected.fileName}</h2><div style={{ color: 'var(--color-text-secondary)', whiteSpace: 'pre-wrap' }}>{selected.notes || 'Chưa có ghi chú.'}</div><div style={{ color: 'var(--color-text-muted)', marginTop: 8 }}>Thành viên: {selected.memberName || 'Toàn dòng họ'}</div>{canManage && <button className="btn btn-sm" style={{ marginTop: 16, color: '#ef4444' }} onClick={() => remove(selected)}>Xóa ảnh</button>}</div></div>}
    </main></div>;
}
